### ISSUE TITLE
Zipline API compatibility task

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#1047]
Right now it’s too easy to accidentally introduce backwards-incompatible changes in `ZiplineService` APIs. Let’s add some tooling to help developers avoid unexpected API breaks.

### api/zipline-api.toml

This is a TOML file that contains a text representation of the APIs in a ZiplineService. It looks like this:

```
[app.cash.zipline.internal.EndpointService]
  
functions = [
   // val serviceNames: Set<kotlin.String>
   "abc21acx", 

   // fun serviceType(kotlin.String): app.cash.zipline.internal.SerializableZiplineServiceType?
   "1acbabc2", 

   // fun supertypeFunction(kotlin.String): app.cash.zipline.internal.SerializableZiplineServiceType?
   "zclj20az", 
]
```

We have a TOML section for each `ZiplineService` declared. In each such section, there is a `functions` array that contains all functions declared by the service and all of its supertypes. The functions are described by their signature hash with a TOML comment containing the function signature string.

### ziplineApiDump

1. This task collects the ZiplineService implementations in the current module.
2. Next it loads the Zipline API file. If the file exists, it confirms that the current API is a superset of the API in the file.
3. Finally it writes an updated Zipline API file.

### ziplineApiCheck

1. This task collects the ZiplineService implementations in the current module.
2. Next it loads the Zipline API file.
3. Finally it crashes if the current API does not exactly match the Zipline API file.

**Comment by swankjesse** [comment]
* [x] Follow Redwood’s lead and expose the API dump stuff in a CLI, then get the Gradle task to call that. That ensures it gets its own classpath and won‘t interfere with any Gradle things.

**Comment by swankjesse** [comment]
* [ ] Run the check task for every target, not just `compileKotlinJvm`. Perhaps write it out on the first target? (We're not guaranteed to have a JVM target).

**Comment by swankjesse** [comment]
I looked into supporting checks on arbitrary compile tasks: JS, Native, etc., and I ran into a pretty ugly snag. The KotlinFirLoader API I stole from Retrofit only works for JVM compiles. Running it on a Kotlin/JS artifact works, but it doesn’t resolve imported symbols like `ZiplineService`.

I’m tempted to leave this part as-is, 'cause the effort to set up a FIR build for each multiplatform target seems high, and the  need to catch breaks in such situations is not urgent.

**Comment by swankjesse** [comment]
Uh oh, I think it’s broken for Java stdlib types.

```
java.lang.IllegalStateException: Class symbol with classId java/io/IOException was not found
        at org.jetbrains.kotlin.util.AnalysisExceptionsKt.wrapIntoFileAnalysisExceptionIfNeeded(AnalysisExceptions.kt:53)
        at org.jetbrains.kotlin.fir.FirCliExceptionHandler.handleExceptionOnFileAnalysis(Utils.kt:172)
        at org.jetbrains.kotlin.fir.resolve.transformers.FirTotalResolveProcessor.process(FirTotalResolveProcessor.kt:97)
        at org.jetbrains.kotlin.fir.pipeline.AnalyseKt.runResolution(analyse.kt:18)
        at org.jetbrains.kotlin.cli.jvm.compiler.pipeline.CompilerPipelineKt.buildResolveAndCheckFir(compilerPipeline.kt:449)
        at org.jetbrains.kotlin.cli.jvm.compiler.pipeline.CompilerPipelineKt.compileModuleToAnalyzedFir(compilerPipeline.kt:407)
        at app.cash.zipline.api.validator.fir.KotlinFirLoader.load(KotlinFirLoader.kt:121)
        at app.cash.zipline.api.validator.fir.FirZiplineApiReaderKt.readFirZiplineApi(FirZiplineApiReader.kt:48)
```

**Comment by JakeWharton** [comment]
There's a TODO waiting for you to figure out and for me to steal!

**Comment by swankjesse** [comment]
# 🎄🎁

**Comment by swankjesse** [comment]
This is done.
