### ISSUE TITLE
Support the K2 compiler

### ISSUE THREAD

**Issue by colinrtwhite** [cashapp/zipline#1086]
Add support for the [new K2 compiler](https://blog.jetbrains.com/kotlin/2023/02/k2-kotlin-2-0/).

Blocked by: https://youtrack.jetbrains.com/issue/KT-59071/K2-MPP-internal-declarations-from-common-module-are-invisible-in-dependent-source-sets-if-there-is-more-that-one-intermediate

**Comment by swankjesse** [comment]
This is done.
