### ISSUE TITLE
Need for Expect/Actual in ZiplineCache.

### ISSUE THREAD

**Issue by Shabinder** [cashapp/zipline#1100]
<img width="1078" alt="image" src="https://github.com/cashapp/zipline/assets/44765050/314d552f-fabf-4a0d-8014-e62aca9ba6ca">

See Above Image for Init and error details.

```
e: file:///Users/shabinder/SoundBound/common/shared/src/commonMain/kotlin/in/shabinder/shared/extension/ExtensionManager.kt:87:32 None of the following functions can be called with the arguments supplied: 
internal constructor ZiplineCache(driver: SqlDriver, database: Database, fileSystem: FileSystem, directory: Path, maxSizeInBytes: Long) defined in app.cash.zipline.loader.ZiplineCache
public fun ZiplineCache(context: Context, fileSystem: FileSystem, directory: Path, maxSizeInBytes: Long): ZiplineCache defined in app.cash.zipline.loader
```

**Comment by Shabinder** [comment]
Expect/Actual was needed, 
Documentation can be improved for this, since IDE doesnt throw any errors until compilation for this.

Or use Androidx.Startup to get a reference of context if thats something that would suit as well.

**Comment by swankjesse** [comment]
This is working as intended. You’ve gotta do this expect/actual work in your own code.
