### ISSUE TITLE
Ensure our builds are 16kb compliant

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/zipline#1243]
https://source.android.com/docs/core/architecture/16kb-page-size/16kb

There's some compilation flags to align to this size that I can't find stated publicly yet. Probably get more info once the Android 15 preview drops.

**Comment by swankjesse** [comment]
Without this we’re getting this crash running Zipline on Android 15 / API level 35.

```
java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/~~ZxUFcGuDQcv9ij_KMRXCVQ==/app.cash.zipline.test-K-VxaF1awxuos15EVjM0lQ==/lib/arm64/libquickjs.so" (new hash type from the future?)
```

**Comment by swankjesse** [comment]
This guide had the goods:
https://developer.android.com/guide/practices/page-sizes#cmake
