### ISSUE TITLE
Zipline.close() should be calling Endpoint.disconnect()

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#1278]
Looks like we might have a leak otherwise?

**Comment by jingibus** [comment]
Would this fix address the root cause of the leaks? `inboundChannel` does retain a bunch of services, but `inboundChannel` *itself* is also leaking. Small potatoes compared to the services, but y'know... always better to strike at the root...

**Comment by swankjesse** [comment]
Fixed by https://github.com/cashapp/zipline/pull/1315
