### ISSUE TITLE
Run Zipline in iOS not on Main Dispatcher

### ISSUE THREAD

**Issue by evtuhovaleksander** [cashapp/zipline#1348]
Hello

We are trying to run Zipline in iOS not on Main Dispatcher (current example uses MainScope and Main Dispatcher).
If we use Main Dispatcher and start some difficult task in out Zipline Service we will face freeze of app's main thread which strongly prohibited.

However if we pass any other Dispatcher to ZiplineLoader
-Default
-newSingleThreadContext("***")

we face crash during loading zipline

```
EXC_BAD_ACCESS (code=2, address=0x1701450d0)

on line in QuickJS.kt in nativeMain SourceSet

312 val value = JS_EvalFunction(context, obj)

```

Maybe we re do something wrong. Please advice? how to properly setup and call Zipline service in the way that QuickJS instance can use not main queue of app

**Comment by JakeWharton** [comment]
We are running Zipline on a background thread on iOS. The setup code for that thread is here: https://github.com/cashapp/redwood/blob/0c17fc1a593fcd310091d38f7f79b9bc696a4396/redwood-treehouse-host/src/iosMain/kotlin/app/cash/redwood/treehouse/IosTreehouseDispatchers.kt. Of note is that the stack size needs bumped significantly.

We should probably change the sample in this repo to use a background thread as well.

**Comment by evtuhovaleksander** [comment]
We have already found that sample code) Thank you very much. 
Very elegant solution
