### ISSUE TITLE
Missing JNI Libraries

### ISSUE THREAD

**Issue by dedechandran** [cashapp/zipline#1409]
Hi, according to [TROUBLESHOOTING.md](https://github.com/cashapp/zipline/blob/trunk/TROUBLESHOOTING.md#missing-jni-libraries) docs, we need to download latest published JVM JAR in the release page, but I couldnt find it. Can someone help me about this? 

Thank you.

**Comment by dedechandran** [comment]
Hi guys, is there any update about this? thank you.

**Comment by JakeWharton** [comment]
You can get a jar from the latest `trunk` build: https://github.com/cashapp/zipline/actions/workflows/build.yaml?query=branch%3Atrunk

I'm not sure why we stopped attaching them onto the releases.

You can also build the native libraries yourself by running one of the two `build-*` scripts in `.github/workflows/`.

**Comment by dedechandran** [comment]
> You can get a jar from the latest `trunk` build: https://github.com/cashapp/zipline/actions/workflows/build.yaml?query=branch%3Atrunk
> 
> I'm not sure why we stopped attaching them onto the releases.
> 
> You can also build the native libraries yourself by running one of the two `build-*` scripts in `.github/workflows/`.

Thanks a lot, will try it.
