### ISSUE TITLE
compileDevelopmentExecutableKotlinJsZipline acts as compileDevelopmentExecutableKotlinJs

### ISSUE THREAD

**Issue by QuasiStellar** [cashapp/zipline#1416]
Works as intended on version 1.9:

`compileDevelopmentExecutableKotlinJsZipline` task generates a `kotlinZipline` folder with `zipline` files and a manifest.

Breaks on version 1.16:

`compileDevelopmentExecutableKotlinJsZipline` task generates a `kotlin` folder with `js` files, exactly like the `compileDevelopmentExecutableKotlinJs` task.

Same with the corresponding production task.

**Comment by JakeWharton** [comment]
Are you sure you're looking in the right place? The folder location of the final assets (and thus our sibling folder) moved in Kotlin 2.0. You can read about it here: https://kotlinlang.org/docs/whatsnew20.html#changes-to-compilation-tasks. So long as you're using the `outputDirectory` of the task the location should always be correct. You can also just feed the whole task into a `FileCollection` and Gradle will take care of pulling from the output directory automatically. Here's an example of us doing that: https://github.com/cashapp/redwood/blob/d540d8ef0730e7b7d2400cddf1c0ce33cf1ec677/build-support/src/main/kotlin/app/cash/redwood/buildsupport/RedwoodBuildPlugin.kt#L576

**Comment by QuasiStellar** [comment]
Yeah, the location of the development build changed to `/build/zipline/Development`. Thanks for the help.
