### ISSUE TITLE
Profiler produces blank results

### ISSUE THREAD

**Issue by QuasiStellar** [cashapp/zipline#1421]
I can't figure out how to get the [profiler](https://github.com/cashapp/zipline/tree/trunk/zipline-profiler) to work. [This](https://github.com/cashapp/zipline/blob/b7c222a6e21d5f3a60c76647a85cb8b80add7e14/zipline-profiler/src/commonTest/kotlin/app/cash/zipline/profiler/SamplingProfilerTest.kt#L131) seems to be the only example on the whole internet and it shows how to profile plain js. Is there a point in that? How do you profile your actual kotlin-js code?

The readme has this piece of code:
```
zipline.quickJs.startCpuSampling(fileSystem, "zipline.hprof".toPath()).use {
  // ...use Zipline...
}
```
What does "use Zipline" mean exactly? I tried to use it like this:
```
runBlocking(mySingleThreadDispatcher) {
    val quickJs = QuickJs.create()
    quickJs.startCpuSampling(FileSystem.SYSTEM, "zipline.hprof".toPath()).use {
        myZiplineService.someMethod()
    }
}
```
and got an empty `zipline.hprof`

**Comment by JakeWharton** [comment]
You need to use the `QuickJs` instance that comes from your `Zipline` instance. In that code, you are creating a new `QuickJs` instance and then calling a service functinon that runs in a different instance.

**Comment by QuasiStellar** [comment]
Thanks, it works now. Please consider adding this to the documentation.
