### ISSUE TITLE
Requesting support for Linux ARM

### ISSUE THREAD

**Issue by SAKET3901** [cashapp/zipline#1479]
I am trying to build on Linux ARM machine but getting this error

`Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: Unable to read /jni/aarch64/libquickjs.so from JAR [in thread "DefaultDispatcher-worker-1"]
                at app.cash.zipline.QuickJsNativeLoaderKt.loadNativeLibrary(QuickJsNativeLoader.kt:36)
                at app.cash.zipline.QuickJs.<clinit>(QuickJs.kt:36)
                ... 9 more
        Suppressed: java.lang.NoClassDefFoundError: Could not initialize class app.cash.zipline.QuickJs
                ... 9 more`

| Header | Header |
|--------|--------|
| ![Image](https://github.com/user-attachments/assets/8c889057-63d8-4fcc-a3c7-0a1005c5374e) | ![Image](https://github.com/user-attachments/assets/ea7cc6a9-60a0-4c90-8500-f0c77c4e82ff) |

On further deep diving found out that from the zipline implementation that ARM is not supported and it’s building only for linux amd 64.
https://github.com/cashapp/zipline/blob/b32e6ec85735341e3a4b0522631b93edcd11fe29/.github/workflows/release.yaml

**Requesting support for Linux ARM**

**Comment by JakeWharton** [comment]
On it
