### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Shuijwan** [cashapp/zipline#170]
The quickjs build failed with the following error.

/Users/Aaron/Documents/workspace/duktape-android/quickjs/src/main/jni/JavaMethodProxy.cpp:54:52: error: cannot initialize a parameter of type 'jvalue *' with an lvalue of type 'const jvalue *'
            env->CallVoidMethodA(javaThis, methodId, args);
                                                     ^~~~
  /Users/Aaron/Library/Android/sdk/ndk-bundle/sysroot/usr/include/jni.h:638:67: note: passing argument to parameter 'args' here
      void CallVoidMethodA(jobject obj, jmethodID methodID, jvalue* args)
                                                                    ^
  /Users/Aaron/Documents/workspace/duktape-android/quickjs/src/main/jni/JavaMethodProxy.cpp:65:66: error: cannot initialize a parameter of type 'jvalue *' with an lvalue of type 'const jvalue *'
            result.z = env->CallBooleanMethodA(javaThis, methodId, args);
                                                                   ^~~~
  /Users/Aaron/Library/Android/sdk/ndk-bundle/sysroot/usr/include/jni.h:620:5: note: passing argument to parameter 'args' here
      CALL_TYPE(jboolean, Boolean)
      ^
  /Users/Aaron/Library/Android/sdk/ndk-bundle/sysroot/usr/include/jni.h:617:5: note: expanded from macro 'CALL_TYPE'
      CALL_TYPE_METHODA(_jtype, _jname)
      ^
  /Users/Aaron/Library/Android/sdk/ndk-bundle/sysroot/usr/include/jni.h:611:17: note: expanded from macro 'CALL_TYPE_METHODA'
          jvalue* args)                                                       \
                  ^
  /Users/Aaron/Documents/workspace/duktape-android/quickjs/src/main/jni/JavaMethodProxy.cpp:78:62: error: cannot initialize a parameter of type 'jvalue *' with an lvalue of type 'const jvalue *'
            result.i = env->CallIntMethodA(javaThis, methodId, args);
                                                               ^~~~
  /Users/Aaron/Library/Android/sdk/ndk-bundle/sysroot/usr/include/jni.h:624:5: note: passing argument to parameter 'args' here
      CALL_TYPE(jint, Int)
      ^
  /Users/Aaron/Library/Android/sdk/ndk-bundle/sysroot/usr/include/jni.h:617:5: note: expanded from macro 'CALL_TYPE'
      CALL_TYPE_METHODA(_jtype, _jname)
      ^
  /Users/Aaron/Library/Android/sdk/ndk-bundle/sysroot/usr/include/jni.h:611:17: note: expanded from macro 'CALL_TYPE_METHODA'
          jvalue* args)                                                       \
                  ^
  /Users/Aaron/Documents/workspace/duktape-android/quickjs/src/main/jni/JavaMethodProxy.cpp:91:65: error: cannot initialize a parameter of type 'jvalue *' with an lvalue of type 'const jvalue *'
            result.d = env->CallDoubleMethodA(javaThis, methodId, args);
                                                                  ^~~~
  /Users/Aaron/Library/Android/sdk/ndk-bundle/sysroot/usr/include/jni.h:627:5: note: passing argument to parameter 'args' here
      CALL_TYPE(jdouble, Double)
      ^
  /Users/Aaron/Library/Android/sdk/ndk-bundle/sysroot/usr/include/jni.h:617:5: note: expanded from macro 'CALL_TYPE'
      CALL_TYPE_METHODA(_jtype, _jname)
      ^
  /Users/Aaron/Library/Android/sdk/ndk-bundle/sysroot/usr/include/jni.h:611:17: note: expanded from macro 'CALL_TYPE_METHODA'
          jvalue* args)                                                       \
                  ^
  /Users/Aaron/Documents/workspace/duktape-android/quickjs/src/main/jni/JavaMethodProxy.cpp:104:65: error: cannot initialize a parameter of type 'jvalue *' with an lvalue of type 'const jvalue *'
            result.l = env->CallObjectMethodA(javaThis, methodId, args);
                                                                  ^~~~
  /Users/Aaron/Library/Android/sdk/ndk-bundle/sysroot/usr/include/jni.h:619:5: note: passing argument to parameter 'args' here
      CALL_TYPE(jobject, Object)
      ^
  /Users/Aaron/Library/Android/sdk/ndk-bundle/sysroot/usr/include/jni.h:617:5: note: expanded from macro 'CALL_TYPE'
      CALL_TYPE_METHODA(_jtype, _jname)
      ^
  /Users/Aaron/Library/Android/sdk/ndk-bundle/sysroot/usr/include/jni.h:611:17: note: expanded from macro 'CALL_TYPE_METHODA'
          jvalue* args)                                                       \
                  ^
  5 errors generated.

**Comment by JakeWharton** [comment]
What version of the NDK are you using?

**Comment by Shuijwan** [comment]
I just update my NDK to r21 beta2 recently, this build error has gone. But I met another build error which said `/Users/Aaron/Documents/workspace/LayoutManager/javascriptcore/src/main/quickjs/quickjs/quickjs.c:1349:12: warning: implicit declaration of function 'malloc_usable_size' is invalid in C99 [-Wimplicit-function-declaration]
    return malloc_usable_size(ptr);
           ^
/Users/Aaron/Documents/workspace/LayoutManager/javascriptcore/src/main/quickjs/quickjs/quickjs.c:1423:31: error: use of undeclared identifier 'malloc_usable_size'
    (size_t (*)(const void *))malloc_usable_size,
`
I just change the use of "malloc_usable_size" to "return 0" and "NULL" according to the comments.

**Comment by swankjesse** [comment]
No action to take on this.
