### ISSUE TITLE
Add test/sample for reusable bridging mechanism

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/zipline#345]
It looks like `FlowReference` and its general-purpose mechanism will be going away. Let's make sure the use case of supporting a custom type is still possible/easy.

**Comment by swankjesse** [comment]
Obsoleted by `ZiplineService`, `ziplineServiceSerializer()`, and pass-by-reference.

**Comment by swankjesse** [comment]
With https://github.com/cashapp/zipline/pull/491 the only interesting thing left is how flows’ elements are serialized with JSON. Implementing https://github.com/cashapp/zipline/issues/420 will reduce the remaining boilerplate in bridging flows.
