### ISSUE TITLE
The pending job will not execute when use await

### ISSUE THREAD

**Issue by 2houyu** [cashapp/zipline#346]
qjs.evaluate("console.log(\"start test\");\n" +
          "function testAsync(params) {\n" +
          "    console.log(\"test Async start\");\n" +
          "    return new Promise(function (resolve, reject) {\n" +
          "        resolve(\"done\");\n" +
          "    });\n" +
          "}\n" +
          "\n" +
          "async function main(){\n" +
          "    var t = await testAsync(11);\n" +
          "    console.log(\"test finish \"+t);\n" +
          "}\n" +
          "main();","test.js");

when test the code above ,the output is below:
--start test
--test Async start

the "test finish" log will not print

**Comment by swankjesse** [comment]
We’ve got similar patterns working when you’re using Kotlin as your source language. This works because we implement `setTimeout()` and Kotlin async primitives use that internally.

Does this work for you?

**Comment by JakeWharton** [comment]
QuickJS does not have an event loop. Zipline does. This solves for coroutines, but I'm not sure it solves for promises. We may need to tick QuickJS's internal event loop so that promise lifecycle's progress.

**Comment by swankjesse** [comment]
No further action here.

**Comment by JakeWharton** [comment]
No? If promises are broken in zipline that's a bug.
