### ISSUE TITLE
Kotlin line numbers in stack traces

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#352]
Our stack traces currently emit line numbers of JavaScript files, which I consider to be an intermediate form.

It’d be really nice for our stack traces to have proper line numbers from the original Kotlin.

We need a mapping file from the Kotlin/JS compiler. Ideally such a file would map JavaScript line numbers to the corresponding Kotlin file name and line number. (Does this exist already?)

We also need a way to provide this mapping to QuickJS. Ideally we could pass a mapping function when we load JavaScript source. Alternatively we could rewrite QuickJS bytecode to fixup line numbers.

**Comment by JakeWharton** [comment]
> Does this exist already?

Yes. A standard source map file is produced adjacent to the .js.

**Comment by swankjesse** [comment]
https://github.com/cashapp/zipline/pulls

**Comment by swankjesse** [comment]
https://github.com/cashapp/zipline/pull/363

**Comment by swankjesse** [comment]
Nothing further needed here!
