### ISSUE TITLE
java.lang.NoClassDefFoundError: app.cash.zipline.QuickJs

### ISSUE THREAD

**Issue by sschemer** [cashapp/zipline#360]
I used QuickJs in my andrid app. 

After i upgrade quickjs to zipline `app.cash.zipline:zipline:0.1.0`, and changed to new package name.
It will throw NoClassDefFoundError when calling `QuickJs.create()`.

**Comment by JakeWharton** [comment]
Yes the released version of Zipline is broken and very, very old. You will need to use a SNAPSHOT build until we release a new version. I think we're getting to a steady state where a 0.2.0 would be warranted within a week or two. The project is in a bit of limbo transitioning between QuickJS and Zipline and we still need to do things like update the README before it's fully ready for public consumption.

**Comment by sschemer** [comment]
@JakeWharton Thanks for your reply.
