### ISSUE TITLE
Throw the right exceptions with useful information 

### ISSUE THREAD

**Issue by kevincianfarini** [cashapp/zipline#402]
It's hard to know what's going on in zipline when an API changes. We should throw the correct `NoSuchMethodError` if nothing can be resolved properly. 

```
NoSuchMethodError:
  invoked:
    ZiplineTreehouse.getScreen(String): ZiplineReference<ZiplineTreehouseUi>
  candidates:
    ZiplineTreehouse.getScreen(String, Navigator): ZiplineReference<ZiplineTreehouseUi>
    ZiplineTreehouse.doTheThing(String, Navigator): ZiplineReference<ZiplineTreehouseUi>
    ZiplineTreehouse.close(): ZiplineReference<ZiplineTreehouseUi>

```

**Comment by swankjesse** [comment]
Currently our bridge function, `CallChannel.invoke()` returns a value (`v`), a null (`n`), or a throwable (`t`).

Let’s add a 4th option, `u` for _Unknown Method_ that includes as its argument a String containing the supported functions. Then the outbound bridge is responsible for converting that list into an appropriate exception.

**Comment by swankjesse** [comment]
@veyndan all done on this?

**Comment by veyndan** [comment]
Yep, not sure why https://github.com/cashapp/zipline/pull/409#issue-1120836000 didn't auto close this issue. Perhaps it's because it didn't get merged into trunk directly 🤷
