### ISSUE TITLE
Do the right thing on interface functions with default parameters

### ISSUE THREAD

**Issue by veyndan** [cashapp/zipline#406]
Suppose we have this interface:

```kotlin
interface EchoService: ZiplineService {
  fun echo(message: String): String
}
```

Then we add a default parameter:

```kotlin
interface EchoService: ZiplineService {
  fun echo(message: String, repeat: Int = 1): String
}
```

Zipline should treat the function with a default parameter as if `@JvmOverloads` has been applied; that is, it should treat it as two functions; one with one parameter and one with two.

```kotlin
interface EchoService: ZiplineService {
  fun echo(message: String): String = echo(message, repeat = 1)
  fun echo(message: String, repeat: Int): String
}
```

**Comment by JakeWharton** [comment]
I don't think that approach works.

For example:
```kotlin
interface Whevs {
  fun foo(one: String, two: String = "two", three: String = "three")
}

whevs.foo("one", three = "four")
```
What happens here?

For each function with default argument values I think you'll want to treat it as two functions: one with the full signature and one with additional bitmask/marker parameters indicating which arguments are set and which are not. This is how the function is handled in JVM bytecode and I suspect similar things are done for JS and native (if not _exactly_ the same thing).

**Comment by swankjesse** [comment]
I don’t think we’ll take further action on this. If we want default parameters, we can create extension functions that delegate.
