### ISSUE TITLE
Zipline JVM artifacts assume Macs are X64

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#418]
I’m getting failures like this from our internal releases:
```
> /private/var/folders/6n/t4d4n1c506d9m_l6t331gftm0000gn/T/quickjs12749920372263119972.tmp: dlopen(/private/var/folders/6n/t4d4n1c506d9m_l6t331gftm0000gn/T/quickjs12749920372263119972.tmp, 0x0001): tried: '/private/var/folders/6n/t4d4n1c506d9m_l6t331gftm0000gn/T/quickjs12749920372263119972.tmp' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/quickjs12749920372263119972.tmp' (no such file)
```

**Comment by JakeWharton** [comment]
Yes we don't build ARM for any OS and have merely relied on having zero Windows ARM users and zero Linux ARM users. I guess Apple broke the camels back.

There are no Mac ARM Action workers (https://github.com/actions/virtual-environments/issues/2187), but hopefully the Zig C cross-compiler support that Ive been meaning to rewrite our builds to use can target ARM (for all three OS's).

**Comment by JakeWharton** [comment]
> When it comes to macOS, Zig even has a custom built linker able to cross-compile for both Intel and Apple Silicon M1, something that not even lld (LLVM's linker) can do. 

Hell yessss

**Comment by swankjesse** [comment]
This seems to work?
https://github.com/cashapp/zipline/pull/419

**Comment by swankjesse** [comment]
Small wrinkles in #419 that I’m not very happy with:
 * How do I test GitHub actions??
 * The archicture used by M1 Macs is `aarch64` in the JVM’s `os.arch`, but `arm64` in cmake, so we need a mapping.
 * Duplication between build.yml and release.yml

**Comment by JakeWharton** [comment]
Actions run on every commit. No need to make a PR.

**Comment by JakeWharton** [comment]
```
$ zig build && file zig-out/lib/libquickjs.dylib
zig-out/lib/libquickjs.dylib: Mach-O 64-bit dynamically linked shared library x86_64

$ zig build -Dtarget=aarch64-macos-gnu && file zig-out/lib/libquickjs.dylib
zig-out/lib/libquickjs.dylib: Mach-O 64-bit dynamically linked shared library arm64
```
Still a ~day's worth of work here but Zig's cross-compilation game is strong. In theory I can build both of those targets from a linux action so we can eliminate the matrix build, too. And hopefully add Windows support.

**Comment by JakeWharton** [comment]
@swankjesse is this fixed? I'd still love to land Zig, but I haven't had time to play with it.

**Comment by swankjesse** [comment]
Fixed.
