### ISSUE TITLE
Zipline loader SQL driver usage lacks inversion of control

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/zipline#439]
* JVM forced to use in-memory database preventing persistence
 * Android forced to use a single filename preventing multiple distinct loaders and in-memory usage for testing

The expect/actual assumes the driver will vary only by the platform it is running on, but the path needs elevated to the caller.

**Comment by swankjesse** [comment]
Done here:
https://github.com/cashapp/zipline/pull/557
