### ISSUE TITLE
ZiplineLoader should get resources from assets/ or res/raw/ on Android

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#442]
We’re currently using jar resources, but we could get better performance by using these instead. They don't suffer memory mapping problems of reading jar resources.

**Comment by JakeWharton** [comment]
Filed upstream, too: https://github.com/square/okio/issues/1097

**Comment by swankjesse** [comment]
No action to take in Zipline on this. Will do in the application layer or Okio.
