### ISSUE TITLE
[Question] Composables in Zipline

### ISSUE THREAD

**Issue by matt-ramotar** [cashapp/zipline#459]
Hey team - Version 1.2 of Compose Multiplatform will support material and UI on JS and iOS. Will passing Composables by Zipline be possible in future?

**Comment by JakeWharton** [comment]
We have been running Compose inside the QuickJS VM for a year now. But this is not Compose UI because QuickJS has no place to render. We run a custom applier with custom nodes and send those across the VM boundary (well, technically we send diffs to keep two trees in sync).

What are you trying to accomplish? I suspect it will always be impossible to run Compose UI inside QuickJS.

**Comment by JakeWharton** [comment]
More specifically, it can't run either Compose UI (Google's material implementation) nor Compose Web (JetBrains' DOM implementation) unless you implement a significant amount of the APIs a browser provides. You can no more use Zipline to run either of them than you can use node.js, but both can run the core Compose runtime just fine.

**Comment by matt-ramotar** [comment]
For context I am building a system to enable design iteration without app release. The system is made up of a (1) [KMP OSS library called "Component Box"](https://github.com/dropbox/componentbox) and a (2) no-code WYSIWYG app for non-engineer usage. The Component Box rendering engine is at the primitive level. By “primitive level” I mean irreducible components like Text and containers of irreducible components like Box. The Component Box components map to Compose and SwiftUI classes. At a minimum the system requires an API that can serve static JSON and JS.


My objective is to increase the velocity of our design iteration. Currently Zipline gives us flexibility to change presentation via server. However the Component Box rendering engine lives on the client. If we want to change it we need to release a new build. My thought was - How cool would it be if we could commit the rendering engine to server also?

**Comment by JakeWharton** [comment]
I'm not familiar with the specific project, but moving the rendering would require that it was written in common code (or JS code) and speak to the host platform over well-defined interfaces bound as services. Is it possible? Absolutely. But I expect it to be very challenging to pull this off in a way that scales to a large application as it likely will require a full graphics API between the JS and host.

**Comment by matt-ramotar** [comment]
Thanks for answering questions Jake - Component Box is first OSS project I own at Dropbox. Mike Nakhimovich (at Twitter now), Sam Edwards, and Ryan Harter are mentors. I will close this but would love to keep you and team in loop as we integrate Zipline if OK?
