### ISSUE TITLE
Use Spotless

### ISSUE THREAD

**Issue by veyndan** [cashapp/zipline#516]
I've noticed that some PRs are implementing one thing but then tidying up the formatting/adding license headers to seeming unrelated files (which [is awesome](https://wiki.c2.com/?BoyScoutRule)) but I think we can slightly reduce the cognitive load of the reviewers by enforcing that these things are fixed (as much as possible) at the time of implementation. We can use [Spotless](https://github.com/diffplug/spotless/tree/main/plugin-gradle) to fix the formatting via [ktlint](https://github.com/diffplug/spotless/tree/main/plugin-gradle#ktlint) and [enforce license headers](https://github.com/diffplug/spotless/tree/main/plugin-gradle#license-header).

**Comment by swankjesse** [comment]
Make it so.
