### ISSUE TITLE
Checking out your broken repo things worked fine for me:

### ISSUE THREAD

**Issue by Benny6731** [cashapp/zipline#552]
Checking out your broken repo things worked fine for me:

```
$ ./gradlew build
BUILD SUCCESSFUL in 6m 2s
210 actionable tasks: 210 executed
```

potentially the build folder just got corrupt on your machine and deleting build would fix it, but otherwise looks like things are fine

_Originally posted by @AlecStrong in https://github.com/cashapp/sqldelight/issues/3239#issuecomment-1127776086_

**Comment by Christopher11487** [comment]
Yeah
