### ISSUE TITLE
Add version to Manifest (default it to Git SHA)

### ISSUE THREAD

**Issue by adrw** [cashapp/zipline#574]
It would be useful to have a stable identifier for the version of the application being run. By default, we can use the Git SHA for the version.

**Comment by JakeWharton** [comment]
It's probably safer to hash the inputs as you cannot assume someone is using Git.

**Comment by adrw** [comment]
@swankjesse Does this end up just being the code signature?

**Comment by swankjesse** [comment]
Inside our build.gradle files we can add something that calls this: `git rev-parse --verify HEAD`
