### ISSUE TITLE
More policy in ZiplineLoader

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#617]
We’ve been struggling to find the right balance of capability vs. complexity in ZiplineLoader and how it works for different use cases:

 * Wait for fresh code – for users who need the freshest code
 * Fast pixels – for users who don't need the freshest code, but do need the fastest launches
 * Always refresh immediately – for development where caching is problematic

After a design exploration @adrw and I have figured out we'll express these options using 2 parameters and a flow parameter.

```
  /**
   * Loads code from [manifestUrlFlow] each time it emits, skipping loads if
   *
   *  * the code to load is too old, or
   *  * the code to replace is too young
   *
   * These policies prevent wasted work if the flow emits too much.
   *
   * @param oldestCodeToLoad the age of the oldest code that we're willing to load. If we don't have
   *     code that fresh (due to network or whatever) we'll just not have any code and the
   *     application should show a placeholder 'connect to network' screen.
   * @param youngestCodeToClobber if we have code that's this old, we'll replace in a disruptive
   *     way if necessary.
   * @param manifestUrlFlow should use `rebounce` to trigger loads when convenient, such as app
   *     launch, app comes to foreground, network connectivity changes, polling for development.
   */
  fun load(
    applicationName: String,
    manifestUrlFlow: Flow<String>,
    oldestCodeToLoad: Duration = Duration.forever,
    youngestCodeToClobber: Duration = Duration.forever,
    initializer: (Zipline) -> Unit,
  ): Flow<Zipline>

  fun loadOnce(
    applicationName: String,
    manifestUrl: String,
    oldestCodeToLoad: Duration
    initializer: (Zipline) -> Unit,
  ): Zipline {
    return flowOf(manifestUrl, ...)
      .firstOrNull() ?: throw Exception(...)
  }
```

We can map our policies to our parameters.

### oldestCodeToLoad

   * **WAIT_FOR_FRESH_CODE** screens this should be 3 days
   * **FAST_PIXELS** screens this should be 7 days
   * **ALWAYS_REFRESH_IMMEDIATELY** screens this should be 0 seconds

### youngestCodeToClobber

   * **WAIT_FOR_FRESH_CODE** this should be 6 hours
   * **FAST_PIXELS** this should be 7 days
   * **ALWAYS_REFRESH_IMMEDIATELY** this should be 0 seconds

### manifestUrlFlow

   * **WAIT_FOR_FRESH_CODE** emits on launch, and when network connectivity changes
   * **FAST_PIXELS** emits on launch, and when network connectivity changes
   * **ALWAYS_REFRESH_IMMEDIATELY** emits continuously using rebounce

**Comment by swankjesse** [comment]
These new functions should replace our current functions, `loadOrFallBack()` and `loadContinuously()`.

**Comment by adrw** [comment]
# Other Tasks
- [x] New timestamp field in cache is set by download start time, maybe add embedded timestamp based on build time or use null and treat it as usable when Duration.forever.
- [x] Rename cache db file to prevent schema collision during rapid development between Zipline versions
