### ISSUE TITLE
quickjs link  failed in iOS.

### ISSUE THREAD

**Issue by showtestlog** [cashapp/zipline#640]
e: Compilation failed: Linking globals named 'lre_id_start_table_ascii': symbol multiply defined!

 * Source files: 
 * Compiler version info: Konan: 1.6.21 / Kotlin: 1.6.21
 * Output kind: FRAMEWORK

e: java.lang.Error: Linking globals named 'lre_id_start_table_ascii': symbol multiply defined!

> Task :zipline:linkPodDebugFrameworkIosArm64 FAILED
:zipline:linkPodDebugFrameworkIosArm64 (Thread[Execution worker for ':' Thread 7,5,main]) completed. Took 8.931 secs.

**Comment by JakeWharton** [comment]
This is when you're building Zipline yourself locally? If so, what SHA?

Or is this when you're consuming our Zipline release? And if so, what version?

**Comment by showtestlog** [comment]
The master branch, And when I use Cocoapods publishing framework, it link bitcode,so it is falied.

**Comment by showtestlog** [comment]
![image](https://user-images.githubusercontent.com/12830799/184123921-f1a31181-51f4-4d23-918e-fb403670f21a.png)

**Comment by showtestlog** [comment]
java.lang.Error: Linking globals named 'lre_id_start_table_ascii': symbol multiply defined!
        at org.jetbrains.kotlin.backend.konan.llvm.DefaultLlvmDiagnosticHandler.handle(diagnosticReport.kt:24)

![image](https://user-images.githubusercontent.com/12830799/184838880-5c6a1ab9-a512-43e9-9186-1ae8403ef630.png)

**Comment by showtestlog** [comment]
> This is when you're building Zipline yourself locally? If so, what SHA?
  the master  de4b2dada384456dd4d84b69ae2cd3d4fad91621

**Comment by showtestlog** [comment]
@JakeWharton  When I compile iOS bitcode, the symbol duplication problem occurs

**Comment by swankjesse** [comment]
We haven’t observed this. If it continues to be an issue, please report to the Kotlin/Native team at JetBrains!
