### ISSUE TITLE
Nicer syntax for Gradle plugin configuration

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#644]
Today:

```
tasks.withType(ZiplineCompileTask::class) {
  mainFunction.set("com.squareup.cash.treehouse.playground.prepareTreehouse")
}
```

Possible alternative:

```
zipline {
  mainFunction.set("com.squareup.cash.treehouse.playground.prepareTreehouse")
}
```

**Comment by adrw** [comment]
Probably lean on examples like Wire https://github.com/square/wire/blob/master/wire-library/wire-gradle-plugin/src/main/kotlin/com/squareup/wire/gradle/WireExtension.kt

**Comment by JakeWharton** [comment]
https://docs.gradle.org/current/userguide/custom_plugins.html#sec:getting_input_from_the_build has a bit of a more modern example. Basically just an abstract type and `Property`-based properties.
