### ISSUE TITLE
Running  emoj search app demo on iphone crash when start. but success and show emoj on simulator

### ISSUE THREAD

**Issue by showtestlog** [cashapp/zipline#679]
iphone14.8.1

![image](https://user-images.githubusercontent.com/12830799/185747399-f40705fe-bb58-4079-941b-5184cd8a1098.png)

simulator
![image](https://user-images.githubusercontent.com/12830799/185747742-54c50f72-1e41-4f14-9611-8cba3143abd5.png)

**Comment by swankjesse** [comment]
I suspect this is due to the fact that this sample loads code from localhost, and localhost probably isn't serving code on your real device. Fixable by changing the URL to get code from.

**Comment by showtestlog** [comment]
thanks
