### ISSUE TITLE
Refactor ZiplineLoader.withLifecycleEvents to not handle & rethrow

### ISSUE THREAD

**Issue by adrw** [cashapp/zipline#724]
It's certainly not an amazing pattern we got forced into here. Generally you want to handle or rethrow and never both. Maybe the design of `withLifecycleEvents` needs to change a bit in a future change to try and remedy this.

_Originally posted by @JakeWharton in https://github.com/cashapp/zipline/pull/700#discussion_r964885926_

**Comment by swankjesse** [comment]
Obsolete.
