### ISSUE TITLE
`StateFlow` bridging support

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/zipline#726]
`StateFlow`, in contrast to `Flow`, exposes a value synchronously which is critical for use in Compose UI as it means you do not need to introduce a dummy default value while you wait for a `Flow`'s first emission.

**Comment by JakeWharton** [comment]
This doesn't seem possible without a wrapper type.

**Comment by Darrellkincade** [comment]
Darrell Kincade

**Comment by JakeWharton** [comment]
Scopes probably make this possible, again

**Comment by JakeWharton** [comment]
Started this in https://github.com/cashapp/zipline/compare/jw.state-flow.2023-02-01. Unsure if I'll get to finish before going on leave if someone wants to push it over the line.

**Comment by colinrtwhite** [comment]
@JakeWharton I created a separate branch that merges `trunk` into your branch [here](https://github.com/cashapp/zipline/compare/trunk...colin/state_flow). I took a look through and it looks pretty complete + tests pass. What's remaining? Do we want to support `MutableStateFlow`?

**Comment by JakeWharton** [comment]
I believe it just needs some tests to ensure all the mechanics of state flow are honored.
