### ISSUE TITLE
[Application Load Fail] app.cash.zipline.QuickJsException: cannot read property 'dropbox' of undefined

### ISSUE THREAD

**Issue by matt-ramotar** [cashapp/zipline#744]
Hey Zipline friends -

I am updating the Component Box [sample app](https://github.com/dropbox/componentbox/tree/1.0.0-alpha01/samples/campaigns) and hitting a runtime failure in `ZiplineLoader`:

```
FATAL EXCEPTION: main
Process: com.dropbox.componentbox.campaigns, PID: 2412
java.lang.IllegalStateException: loading failed; see EventListener for exceptions
at app.cash.zipline.loader.ZiplineLoader.loadOnce(ZiplineLoader.kt:222)
at app.cash.zipline.loader.ZiplineLoader$loadOnce$1.invokeSuspend(Unknown Source:18)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7898)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c0ebdd9, Dispatchers.Main]
```

I attached a debug `EventListener`. Every download that starts also ends, and my understanding is `downloadEnd()` is invoked only on success. Neither `callStart()` nor `callEnd()` is invoked. On `applicationLoadFailed()` I get:

```
app.cash.zipline.QuickJsException: cannot read property 'dropbox' of undefined
```

Links to relevant code and notes:
- [flowOfModels()](https://github.com/dropbox/componentbox/blob/1.0.0-alpha01/model/src/hostMain/kotlin/com/dropbox/componentbox/model/FlowOfModels.kt) = Lib function responsible for invoking `ziplineLoader.loadOnce()` and returning `Flow<ComponentBoxModel>`
- [ComponentBoxController](https://github.com/dropbox/componentbox/blob/1.0.0-alpha01/model/src/androidMain/kotlin/com/dropbox/componentbox/model/ComponentBoxController.kt) = Lib class responsible for setting up Zipline and invoking `flowOfModels()`. Expected by `hostMain`
- [ComponentBoxPresenter](https://github.com/dropbox/componentbox/blob/1.0.0-alpha01/model/src/androidMain/kotlin/com/dropbox/componentbox/model/ComponentBoxPresenter.kt) = Lib class responsible for creating `ComponentBoxController` and integrating it with Component Box data and events. Expected by `hostMain`
- [main()](https://github.com/dropbox/componentbox/blob/1.0.0-alpha01/samples/campaigns/xplat/componentbox/src/jsMain/kotlin/com/dropbox/componentbox/campaigns/xplat/componentbox/main.kt) - Feature function responsible for binding [CampaignsComponentBoxService](https://github.com/dropbox/componentbox/blob/1.0.0-alpha01/samples/campaigns/xplat/componentbox/src/commonMain/kotlin/com/dropbox/componentbox/campaigns/xplat/componentbox/CampaignsComponentBoxService.kt) to `zipline`
- [AccountCampaignsViewModel](https://github.com/dropbox/componentbox/blob/1.0.0-alpha01/samples/campaigns/android/feature/account/src/main/kotlin/com/dropbox/componentbox/campaigns/android/feature/account/ui/AccountCampaignsViewModel.kt) - Feature view model responsible for launching `CampaignsComponentBoxService`

Can you please take a look or point me in the right direction for root debugging a QuickJsException? 🙏🏽

**Comment by epicadk** [comment]
Not entirely sure but it could be an issue with your main function. You can verify by checking the response from the manifest and the generated js module.  -`build/compileSync/main/developmentExecutable/kotlin`

**Comment by swankjesse** [comment]
This typically indicates that we’re not loading the entry point correctly. What you have in your `build.gradle` file needs to match with a function annotated `@JsExport`.

```
zipline {
  mainFunction.set("app.cash.zipline.samples.trivia.launchZipline")
}
```
