### ISSUE TITLE
Support for protobufs without Kotlin/JS

### ISSUE THREAD

**Issue by baconz** [cashapp/zipline#909]
Would it be reasonable to try to add protobuf support out of the box?

The idea would be that you would install an npm module in your JS project that would allow you to `bind` your protobuf service, and would generate the manifest.

Then on the JVM side you would hook up the `.proto` (ideally with a simple gradle plugin or something).

From that point you'd be able to call into the JS proto service using generated code on the JVM side.

Is this a reasonable feature to try to add? Would you be open to a PR?

**Comment by JakeWharton** [comment]
If you declare your service interface as a proto service and perform codegen based on it on both sides this should mostly just work. The only hiccup is that our bridge is currently JSON based and so you would need to serialize the proto values sent across the bridge as JSON rather than binary.

**Comment by baconz** [comment]
Hmm, perhaps gRPC over JSON is a better fit, then.

The issue with doing the codegen on the `jsMain` side is that you end up incurring the overhead of Kotlin/JS which we've found to be performance-prohibitive. I'm looking for a clean way to bridge JS <=> Kotlin without Kotlin/JS.

**Comment by JakeWharton** [comment]
While we provide access to the underlying QuickJS instance, it's mostly for debugging and our own setup. We don't want to support anything but Kotlin since we plan to abandon JS for WASM at some point. How the two Kotlin interfaces are bridged across the VM boundary is somewhat meant to be an implementation detail.

**Comment by baconz** [comment]
I see. That makes sense.

Just for context, we run on a lot of older JS platforms that don't (and will never) support WASM.

We have a sizable KMM codebase for shared business logic, but have been running into performance issues with Kotlin/JS and are considering exploring the shared logic into JS away from Kotlin.

Since it seems like ya'll are pretty heavily leveraging Kotlin/JS I'm curious if there are tricks you've used to work around the performance issues.

**Comment by JakeWharton** [comment]
I guess it depends on where the performance problems lie. Some things we do off the top of my head:

- Use QuickJS native JSON library that's written in C rather than kotlinx.serialization which is written in Kotlin (and thus runs as JS)
- Avoid the use of `Long` since it gets emulated as two ints in an object.
- Generate specific serialization code for the JS that minimizes boxing and only includes the serialization codepaths we need.
- Use JS-native `Array`, `Set`, and `Map` rather than Kotlin's `List`, `Set`, and `Map` through external interface definitions.
- Precompile the JS to QuickJS bytecode to avoid lexing/parsing step on the clients.

There's probably more but that's all I can think of right now.

**Comment by baconz** [comment]
Thanks, yeah, that all makes sense and we've sort of stumbled into some of those solutions in our code.

The issue is in external dependencies. As a silly example, on our slower devices we see [these constants](https://github.com/ktorio/ktor/blob/main/ktor-http/common/src/io/ktor/http/Codecs.kt#L9) take up to 100ms to instantiate.

I guess maybe the answer is don't use any external dependencies, offload all of the networking to the "native" (JS) client, and rely on `external interface` for data passed in.

Anyway, thanks for the input. Much appreciated!

**Comment by JakeWharton** [comment]
Yeah we use the HTTP client on the host-side (JVM, Android, or iOS) and expose it as an interface to JS with a very simple request object.

**Comment by baconz** [comment]
Makes sense. We ended up wrapping ktor and then providing our own thin wrapper around `fetch()` for browsers.

https://gist.github.com/baconz/9c87a07038cb99eb60fb5d1e2b47e7b1

We still have the problem of turning the `dynamic` into something on the Kotlin/JS side, and in that gist, we're seeing that both `decodeFromDynamic` and `DynamicJsJsonReader` are pretty slow because they leverage Kotlin List/Map.

I feel like somebody should make a paired down set of Kotlin primitives with expect/actuals that are guaranteed to use JS primitives. Like, it would be nice to be able to grab a convenient `NativeMap` that might not have all of the functionality in `kotlin.Map`, but you could be guaranteed that on JS platforms it would use a JS object (or `Map` on ECMA6).

**Comment by JakeWharton** [comment]
Well let me introduce you to https://github.com/JakeWharton/platform-collections!

**Comment by baconz** [comment]
Hey, cool!!!

Any chance of publishing that up to a maven repo somewhere?

I'm curious why you chose not to implement any of the collection iteration convenience methods (eg `map`, `forEach`, `filter` etc etc). Just trying to keep it simple, or something else?

**Comment by JakeWharton** [comment]
Snapshots should be publishing to Sonatype's snapshot repo. It's not quite ready for a first release yet. It's a side project for at work and I'm on leave for another month.

**Comment by baconz** [comment]
Hmm, I'm not seeing anything that's pushing it -- https://github.com/JakeWharton/platform-collections/blob/trunk/.github/workflows/build.yaml

If it is helpful I can push up a PR that adds the publish block the build.yaml and build.gradle. You'd still have to set up your sonatype creds, though.

**Comment by JakeWharton** [comment]
Ah. No I'll do it. I have a million projects to copy from with my most recent setup.

**Comment by swankjesse** [comment]
Great discussion. No further action to take on this!

**Comment by JakeWharton** [comment]
I forgot in which issue we were discussing this, but snapshots for platform-collections are publishing now. I have a little work to do before a 0.1 release but it's (slowly) coming along.

**Comment by baconz** [comment]
Thanks so much! We will start playing around with it!
