### ISSUE TITLE
Ensure we're prepared for adopting `AutoCloseable` from stdlib

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/zipline#999]
We want to be able to make things like `ZiplineService`, `ZiplineScope`, and maybe others extend from `AutoCloseable` once its stable.

This mostly entails making sure we use `close(): Unit` and not something like `cancel()` or something with a non-`Unit` return value.

Checked:
* [x] `ZiplineService`
* [x] `ZiplineScope`

**Comment by swankjesse** [comment]
I audited out public API.
https://github.com/cashapp/zipline/blob/trunk/zipline/api/jvm/zipline.api

The only close-like thing we still have is `CancelCallback`. It needs `cancel()` to remain distinct of `close()` as close is built-in to `ZiplineService` and does something different!
